### ISSUE TITLE
Unsecure

### ISSUE THREAD

**Issue by natesworksold** [kezza2k7/Estopia-Protect#2]
At first glance this doesnt seem secure as you might think. A usb drive bought from the same place/same manufacturer may be detected as the same device.

**Comment by imaoreo** [comment]
But it doesn't even care if it's the same device it just checks for a file login.pass, If this file isn't detected then the computer locks... This is so if your usb breaks and doesn't work it doesn't stop the functionality of your computer.

**Comment by natesworksold** [comment]
Ohhh ok mb
